import logging
from abc import ABC, abstractmethod
from datetime import datetime

from google import genai
from google.genai import types

from src.modules.viewer import Viewer

ranking_review_system_instructions = """
Crie um texto de review dura e sarcástica do dia. O objetivo 
é animar e incentivar os usuários de um ranking de 
contribuições mensais, zuando com eles 
no processo. Eles são seguidores do usuário "{username}" no GitHub. 
Os dados serão fornecidos em um JSON, que também contem 
informações sobre os repositórios recentes onde o usuário 
contribuiu recentemente, atente-se as datas. 
Sinta-se livre para utilizar estes dados como argumentos quando quiser. 
Seja engraçado, passivo-agressivo, faça historinhas, tire sarro, 
humilhe um pouco, caçoe, faça piadas, humor ácido, faça trocadilhos, 
seja sarcástico, sem parecer que você está tentando ser engraçado. 
Sem citar que "isso" é uma zueira, evite questões de gênero, 
política ou sexual. Seja criativo. 
Exemplos de contribuições são: commits, pull requests, 
issues, code review, etc. Você não é o "{username}". Não assuma coisas 
que o "{username}" faria, o objetivo dos usuários não é agradar "{username}", 
"{username}" Não é melhor que ninguém. 
A data atual é {date}, use-a para referência, se necessário.

Instruções para resposta:

- Responda um parágrafo para cada usuário, através de tags HTML.
- Utilize a tag `<p></p>` para parágrafos e nada mais. 
- Voce pode utilizar `<b></b>` para negrito e `<i></i>` para itálico, 
dentro do parágrafo.
- Não utilize blocos de código, estilos, markdown ou outras tags HTML.
- Não se refira aos dados fornecidos em JSON diretamente, como "stargazers", 
"contributions", "followers", etc.
- Até 15 linhas em média.

Modelo de resposta aceitável:

<p>Texto 1</p>
<p><b>Usuário</b>, texto 2</p>
<p>Texto <i>3</i></p>
"""


class AIService(ABC):
    """
    Interface for AI services.

    Methods
    --------
    generate_ranking_review(json_ranking_prompt: str, viewer: Viewer) -> str:
        Abstract method that generates a ranking review based on a JSON prompt
        and a Viewer object.
    """

    @abstractmethod
    def generate_ranking_review(
        self, json_ranking_prompt: str, viewer: Viewer
    ) -> str:
        """
        Abstract method that generates a ranking review based on a JSON prompt
        and a Viewer object.

        Parameters
        ----------
        json_ranking_prompt : str
            A JSON prompt containing information about a ranking.
        viewer : Viewer
            A Viewer object containing information about the user.

        Returns
        -------
        str
            A ranking review generated by the AI service.
        """
        pass


class AI:
    """
    Class that uses an AIService to generate reviews.

    Attributes
    ----------
    ai_service : AIService
        An AIService object used to generate reviews.
    """

    def __init__(self, ai_service: AIService) -> None:
        self.ai_service = ai_service

    def change_service(self, ai_service: AIService) -> None:
        """
        Change the AI service used to generate reviews.

        Parameters
        ----------
        ai_service : AIService
            An AIService object used to generate reviews.
        """

        logging.info(f"Changing AI service to {ai_service.__class__.__name__}")
        self.ai_service = ai_service

    def generate_review(self, json_ranking_prompt: str, viewer: Viewer) -> str:
        """
        Generate a review based on a JSON prompt and a Viewer object.

        Parameters
        ----------
        json_ranking_prompt : str
            A JSON prompt containing information about a ranking.
        viewer : Viewer
            A Viewer object containing information about the user.

        Returns
        -------
        str
            A review generated by the AI service.
        """

        logging.info(
            f"Generating AI review with {self.ai_service.__class__.__name__}"
        )
        return self.ai_service.generate_ranking_review(
            json_ranking_prompt, viewer
        )


class GeminiService(AIService):
    """
    Class that implements the AIService interface using the Gemini API.

    Attributes
    ----------
    api_key : str
        The API key used to access the Gemini API.

    Methods
    -------
    generate_ranking_review(json_ranking_prompt: str, viewer: Viewer) -> str:
        Generates a ranking review based on a JSON prompt and a Viewer object.
    """

    def __init__(self, api_key: str) -> None:
        self.client = genai.Client(api_key=api_key)

    def generate_ranking_review(
        self, json_ranking_prompt: str, viewer: Viewer
    ) -> str:
        """
        Generates a ranking review based on a JSON prompt and a Viewer object.

        Parameters
        ----------
        json_ranking_prompt : str
            A JSON prompt containing information about a ranking.
        viewer : Viewer
            A Viewer object containing information about the user.

        Returns
        -------
        str
            A ranking review generated by the Gemini AI.
        """
        system_prompt = ranking_review_system_instructions.format(
            username=viewer.get_username(),
            date=datetime.now().strftime("%Y-%m-%d"),
        )

        logging.info("Generating ranking review with Gemini AI...")
        response = self.client.models.generate_content(
            model="gemini-2.0-flash",
            contents=types.Part.from_text(text=json_ranking_prompt),
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                temperature=1.8,
                top_p=0.8,
                top_k=40,
                response_mime_type="text/plain",
            ),
        )

        return response.text
