name: 📈 Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:      
      - name: 💻 Most used languages
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          committer_branch: renders-output
          committer_message: "chore: update metrics"
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_colors: typescript:#1b9ff7
          plugin_languages_limit: 10
          base: "languages"
          extras_css: |
            h2.field, h3.field {
                display: none;
            }